### ISSUE TITLE
Correção no readme/sugestão

### ISSUE THREAD

**Issue by twdnl14** [thiago-rezende/docker4noobs#3]
Na instalação do git você poderia colocar mais exemplos de sistemas operacionais(linux é o kernel, não o sistema operacional), como exemplo: fedora e baseados nele, arch, debian e etc

**Comment by thiago-rezende** [comment]
Eu pretendo adiconar exemplos para os sistemas ubuntu, centos e arch em todo o curso.

**Comment by thiago-rezende** [comment]
Fiz a alteração, eu pretendo muda um pouco a estrutura do curso tb, ent eu vou realocar essa parte de setup para um arquivo dedicado e mais detalhado.

**Comment by thiago-rezende** [comment]
Obrigado pela sugestão, e sinta-se a vontade para contribuir com o projeto.

**Comment by thiago-rezende** [comment]
@twdnl14 na aba `projects` do repositório, vc pode ter uma ideia sobre o andamento e as mudanças q eu planejo fazer.
